name: LAB

services:
  router:
    container_name: lab-router
    build:
      context: ./
      dockerfile: ./Dockerfile
    
    networks:
      - docker-network
    
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

networks:
  docker-network:
    driver: bridge