services:
  caddy:
    container_name: lab-caddy
    build: .
    ports:
      - "15565:15565"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: